# Generated by Django 5.1.4 on 2024-12-07 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_name", models.CharField(max_length=100)),
                ("faculty_subject", models.CharField(max_length=100)),
                ("student_count", models.IntegerField()),
                ("total_fees", models.FloatField()),
                ("payable_fees", models.FloatField()),
                ("paid_amount", models.FloatField(default=0.0)),
                ("remaining_amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="StdMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standard_name", models.CharField(max_length=50)),
                ("academic_year", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SubMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("fee_amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_no", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("school_name", models.CharField(max_length=150)),
                ("board", models.CharField(max_length=50)),
                ("medium", models.CharField(max_length=50)),
                ("discount", models.FloatField(default=0.0)),
                ("total_fees", models.FloatField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("Morning", "Morning"), ("Evening", "Evening")],
                        max_length=50,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("paid_amount", models.FloatField(default=0.0)),
                ("remaining_amount", models.FloatField()),
                ("fees_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField()),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("UPI", "UPI"), ("Card", "Card")],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuition.stdmaster",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuition.submaster",
                    ),
                ),
            ],
        ),
    ]
